### ISSUE TITLE
Data collection - civilians - Chetan, Chao and Chen

### ISSUE THREAD

**Issue by sumitmukhija** [sumitmukhija/Sentiment-analysis-study#2]
Filtered vets have 

- 'army' in bio
- 'veteran' in bio
- 'soldier' in bio
- 'military' in bio
- 'organization' not in bio
- 'group' not in bio
- more than 100 tweets
- joined before 2016

Corresponding file - /supporting scripts/filter.py
Line number: 23

Please make sure to have similar constraints in civilians.

**Comment by tannineo** [comment]
Close due to final submission
